# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  # https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#key-input
  - task: Cache@2
    inputs:
      key: 'yarn | "$(Agent.OS)" | yarn.lock'
      restoreKeys: |
        yarn | "$(Agent.OS)"
        yarn
      path: $(YARN_CACHE_FOLDER)
    displayName: Cache Yarn packages

  - script: |
      yarn --frozen-lockfile
    displayName: 'Install Dependecies'

  - script: |
      yarn run build
    env:
      PUBLIC_URL: '/Kubasta/'
    displayName: 'Build React App'

  # https://florian-rappl.de/News/Page/383/azure-pipelines-publish-to-github-pages
  - script: |
      git config user.email "ci@dev.azure.com" 
      git config user.name "Azure DevOps"
      yarn run deploy:gh-pages -r https://$GITHUB_PAT@github.com/GedasFX/Kubasta.git
    env:
      GITHUB_PAT: $(GITHUB_PAT)
    displayName: 'Deploy Website'
